name: Build Docker Compose

on:
  repository_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: services
          path: dist/

      - name: Build docker-compose
        run: docker-compose build

      - name: Run services (test)
        run: docker-compose up -d