name: Build Docker Compose

on:
  repository_dispatch:
    types: [build_completed]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build docker-compose
        run: docker-compose build

      - name: Run services (test)
        run: docker-compose up -d